# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_facial_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='facial_product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
