# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_facial_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facial_product',
            name='image',
            field=models.ImageField(upload_to='facialproducts_upload/%Y/%m/%d/'),
        ),
    ]
